name: Apply

inputs:
  working_dir:
    description: 'The working directory for the Terraform code'
    type: string
    required: false
    default: 'deployments'
  terraform_workspace:
    description: 'The Terraform workspace to use'
    type: string
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@master
      
    - name: Terraform Init
      id: init
      run: terraform init
      working-directory: ${{ inputs.working_dir }}
      shell: bash

    - name: Download Plan Artifact
      uses: actions/download-artifact@v3
      with:
        name: tfplan
        path: ${{ inputs.working_dir }}
      
    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve ${{ inputs.working_dir }}/${{ inputs.terraform_workspace }}.tfplan
      working-directory: ${{ inputs.working_dir }}
      shell: bash