name: Apply

inputs:
  working_dir:
    description: 'The working directory for the Terraform code'
    type: string
    required: false
    default: 'deployments'
  terraform_workspace:
    description: 'The Terraform workspace to use'
    type: string
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@master

    - name: Restore Terraform Plan File
      uses: actions/cache@v3
      with:
        path: ${{ inputs.working_dir }}/${{ inputs.terraform_workspace }}.tfplan
        key: terraform-plan-${{ inputs.terraform_workspace }}
      
    - name: Terraform Init
      id: init
      run: terraform init
      working-directory: ${{ inputs.working_dir }}
      shell: bash
      
    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve ${{ inputs.terraform_workspace }}.tfplan
      working-directory: ${{ inputs.working_dir }}
      shell: bash