name: Validate

inputs:
  working_dir:
    description: 'The working directory for the Terraform code'
    type: string
    required: false
    default: 'deployments'
  workspace:
    description: 'The Terraform workspace to use'
    type: string
    required: true
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@master
    
    - name: Terraform Init
      id: init
      run: terraform init
      working-directory: ${{ inputs.working_dir }}
      shell: bash

    - name: Terraform Workspace
      id: workspace
      run: terraform workspace select ${{ inputs.workspace }} || terraform workspace new ${{ inputs.workspace }}
      working-directory: ${{ inputs.working_dir }}
      shell: bash

    - name: Terraform Validate
      id: validate
      run: terraform validate
      working-directory: ${{ inputs.working_dir }}
      shell: bash

    - name: Tfsec
      id: tfsec
      uses: aquasecurity/tfsec-action@v1.0.3
      with:
        working_directory: ${{ inputs.working_dir }}

    - name: Checkov
      id: checkov
      uses: bridgecrewio/checkov-action@master
      with:
        directory: ${{ inputs.working_dir }}
      continue-on-error: true