name: Build & Run Go

inputs:
  working_dir:
    description: 'The directory to run go build in'
    type: string
    required: false
    default: '.'
  go_version:
    description: 'The version of Go to use'
    type: string
    required: false
    default: '1.19'
  azure_webapp_name:
    description: 'The name of the Azure Web App to deploy to'
    type: string
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@master

    - name: Setup Go
      id: setup-go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.go_version }}

    - name: Build
      id: build
      run: go build
      shell: bash
    
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ inputs.azure_webapp_name }}
        slot-name: 'myGoApp'
        package: .
