name: Build & Run Go

inputs:
  working_dir:
    description: 'The directory to run go build in'
    type: string
    required: false
    default: '.'
  azure_webapp_name:
    description: 'The name of the Azure Web App to deploy to'
    type: string
    required: true
  client_id:
    description: 'Azure Service Principal Client ID'
    type: string
    required: true
  client_secret:
    description: 'Azure Service Principal Client Secret'
    type: string
    required: true
  subscription_id:
    description: 'Azure Subscription ID'
    type: string
    required: true
  tenant_id:
    description: 'Azure Tenant ID'
    type: string
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@master

    - name: Setup Go
      id: setup-go
      uses: actions/setup-go@v5
      with:
        go-version-file: src/go.mod

    - name: Build
      id: build
      run: go build src/main.go -o src/app
      working-directory: ${{ inputs.working_dir }}
      shell: bash

    - name: Az Login
      id: az-login
      uses: azure/login@v2
      with:
        creds: '{"clientId":"${{ inputs.client_id }}","clientSecret":"${{ inputs.client_secret }}","subscriptionId":"${{ inputs.subscription_id }}","tenantId":"${{ inputs.tenant_id }}"}'
    
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ inputs.azure_webapp_name }}
        slot-name: 'myGoApp'
        package: src/app
