name: Deploy Terraform Configuration

on:
  push:
    branches:
      - main
      - stage
      - dev
  workflow_dispatch:
    inputs:
      terraform_workspace:
        description: 'The Terraform workspace to use'
        type: choice
        required: true
        options:
          - prod
          - stage
          - dev

permissions:
  contents: read
  pull-requests: write

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  WORKING_DIR: 'deployments'
  GH_TOKEN: ${{ github.token }}

jobs:
  deploy-production:
    if: github.event_name == 'push' && github.ref_name == 'main' || github.event_name == 'workflow_dispatch' && github.event.inputs.terraform_workspace == 'prod'
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform Apply
        id: apply
        uses: ./.github/actions/apply
        with:
          working_dir: ${{ env.WORKING_DIR }}
          terraform_workspace: 'prod'

  deploy-stage:
    if: github.event_name == 'push' && github.ref_name == 'stage' || github.event_name == 'workflow_dispatch' && github.event.inputs.terraform_workspace == 'stage'
    runs-on: ubuntu-latest
    environment: Stage
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform Apply
        id: apply
        uses: ./.github/actions/apply
        with:
          working_dir: ${{ env.WORKING_DIR }}
          terraform_workspace: 'stage'

  deploy-development:
    if: github.event_name == 'push' && github.ref_name == 'dev' || github.event_name == 'workflow_dispatch' && github.event.inputs.terraform_workspace == 'dev'
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform Apply
        id: apply
        uses: ./.github/actions/apply
        with:
          working_dir: ${{ env.WORKING_DIR }}
          terraform_workspace: 'dev'
