name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      workspace:
        description: 'Workspace to destroy'
        required: true
        type: choice
        options:
          - dev
          - stage
          - prod
      working_dir:
        description: 'Working directory'
        required: false
        type: choice
        default: deployments
        options:
          - deployments
          - backend

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  GH_TOKEN: ${{ github.token }}
  TF_WORKSPACE: ${{ inputs.workspace }}
  WORKING_DIR: ${{ inputs.working_dir }}

jobs:
  destroy:
    name: Destroy Terraform Resources
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@master

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve
        working-directory: ${{ env.WORKING_DIR }}