name: Dev - Deploy to Azure

on:
  push:
    branches:
      - dev
    paths-ignore:
      - '.github/**'
      - 'backend/**'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  TF_VAR_mssql_administrator_login: ${{ secrets.MSSQL_ADMINISTRATOR_LOGIN }}
  TF_VAR_mssql_administrator_login_password: ${{ secrets.MSSQL_ADMINISTRATOR_LOGIN_PASSWORD }}
  GH_TOKEN: ${{ github.token }}
  WORKING_DIR: 'deployments'
  TF_WORKSPACE: 'dev'

jobs:
  validate:
    name: Validate Terraform Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@master

      - name: Terraform validate
        id: validate
        uses: ./.github/actions/validate
        with:
          working_dir: ${{ env.WORKING_DIR }}
          workspace: ${{ env.TF_WORKSPACE }}

  plan:
    name: Plan Terraform Files
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@master

      - name: Terraform plan
        id: plan
        uses: ./.github/actions/plan
        with:
          working_dir: ${{ env.WORKING_DIR }}
          terraform_workspace: ${{ env.TF_WORKSPACE }}

  apply:
    name: Apply Terraform Files
    runs-on: ubuntu-latest
    needs: plan
    environment: Development
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@master

      - name: Terraform apply
        id: apply
        uses: ./.github/actions/apply
        with:
          working_dir: ${{ env.WORKING_DIR }}
          terraform_workspace: ${{ env.TF_WORKSPACE }}

  go:
    name: Build & Run Go
    runs-on: ubuntu-latest
    needs: apply
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@master

      - name: Go
        id: go
        uses: ./.github/actions/go
        with:
          working_dir: '.'
          azure_webapp_name: 'erlenrom-web-dev'
          client_id: ${{ env.ARM_CLIENT_ID }}
          client_secret: ${{ env.ARM_CLIENT_SECRET }}
          subscription_id: ${{ env.ARM_SUBSCRIPTION_ID }}
          tenant_id: ${{ env.ARM_TENANT_ID }}