name: Terraform File Formatting & Soft Validate

on:
  push:
    branches-ignore:
      - dev
      - stage
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  WORKING_DIR: '.'

jobs:
  format:
    name: Format Terraform Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}

      - name: terraform fmt
        id: fmt
        uses: dflook/terraform-fmt@v1.44.0
        with:
          path: ${{ env.WORKING_DIR }}

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "terraform fmt applied"

      - name: Push Changes
        id: push
        run: |
          git push origin ${{ github.ref }}

  soft-validate:
    name: Soft Validate Terraform Files
    runs-on: ubuntu-latest
    needs: format
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@master

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: ${{ env.WORKING_DIR }}

      - name: Tfsec
        id: tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: ${{ env.WORKING_DIR }}
      
      - name: Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ${{ env.WORKING_DIR }}
        continue-on-error: true
