name: Stage - Deploy to Azure

on:
  push:
    branches:
      - stage
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  GH_TOKEN: ${{ github.token }}
  WORKING_DIR: 'deployments'
  TF_WORKSPACE: 'stage'

jobs:
  validate:
    name: Validate Terraform Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@master

      - name: Terraform validate
        id: validate
        uses: ./.github/actions/validate
        with:
          working_dir: ${{ env.WORKING_DIR }}

  plan:
    name: Plan Terraform Files
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@master

      - name: Terraform plan
        id: plan
        uses: ./.github/actions/plan
        with:
          working_dir: ${{ env.WORKING_DIR }}
          terraform_workspace: ${{ env.TF_WORKSPACE }}

  apply:
    name: Apply Terraform Files
    runs-on: ubuntu-latest
    needs: plan
    environment: Stage
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@master

      - name: Terraform apply
        id: apply
        uses: ./.github/actions/apply
        with:
          working_dir: ${{ env.WORKING_DIR }}
          terraform_workspace: ${{ env.TF_WORKSPACE }}

  go:
    name: Build & Run Go
    runs-on: ubuntu-latest
    needs: apply
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@master

      - name: Go
        id: go
        uses: ./.github/actions/go
        with:
          working_dir: 'src'
          go_version: '1.19'
          azure_webapp_name: 'my_go_app'