name: Validate Prod

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  GH_TOKEN: ${{ secrets.IAC_ASSIGNMENT_2_TOKEN }}
  WORKING_DIR: '.'

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Validation
        id: validation
        uses: ./.github/actions/validate
        with:
          WORKING_DIR: ${{ env.WORKING_DIR }}
